class Constant


  CONST_REGISTER_CANDIDATE = "REGISTRO DE CANDIDATO"
  CONST_CANDIDATE_REGISTRED = 'SUS DATOS FUERON REGISTRADOS SATISFACTORIAMENTE. A SU CORREO FUERON ENVIADAS LAS INSTRUCCIONES PARA CONTINUAR EL PROCESO'
  CONST_TYPE_FLASH_MESSAGE_ERROR = 'ERROR'
  CONST_TYPE_FLASH_MESSAGE_SUCESS = 'SUCESS'
  CONST_INTERNAL_SERVER_ERROR = 'ERROR INTERNO EN EL SERVIDOR'
  CONST_INITIAL_PASSWORD = 'CAMBIO DE CONTRASEÑA INICIAL'
  CONST_EMAIL_NO_EXIST = 'EL CORREO DILIGENCIADO NO EXISTE'
  CONST_EMAIL_NOT_NULL = 'NO HA INGRESADO EL CORREO ELECTRONICO'
  CONST_INITIAL_PASSWORD = 'CAMBIO DE CONTRASEÑA INICIAL'
  CONST_PASSWORD_NO_MATCH = 'LAS CONTRASEÑAS INGRESADAS NO COINSIDEN'
  CONST_PASSWORD_NO_LENGHT_REQUIRED = 'LA CONTRASEÑA NO TIENE LA CANTIDAD DE CARACCTERES SOLICITADOS'
  CONST_SECURITY_CODE_DONT_MATCH = 'EL CODIGO DE SEGURIDAD ES INCORRECTO'
  CONST_ALREADY_DONE = 'YA HAS REALIZADO ESTE PROCESO'
  CONTS_PASSWORD_CHANGE = 'CAMBIO DE CONTRASEÑA REALIZADO'
  CONTS_NO_CURRENT_PASSWORD = 'LA CONTRASEÑA INGRESADA NO CORRESPONDE A LA ACTUAL'
  CONTS_USER_PASSWORD_INVALID = 'EL USUARIO O CONTRASEÑA INGRESADOS SON INCORRECTOS'
  CONST_USER_NO_VALID = "USUARIO NO PERMITIDO EN PLATAFORMA"
  CONST_NO_PASSWORD = "DEBE INGRESAR LA CONTRASEÑA"
  CONST_NO_EMAIL = "DEBE INGRESAR EL CORREO ELECTRONICO"
  CONTS_SESION_CLOSE_SUCESS = 'SESIÓN CERRADA CORRECTAMENTE'
  CONST_SECRET_PASSWORD_TOKEN = '12345678'




end